package views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import model.bean.CompraVendaProduto;
import views.utils.Actions;
import model.bean.GenericBean;
import model.dao.querybuilder.GenericDAO;
import views.modal.CompraVendaEditor;
import views.utils.Alerts;

public class CompraVendaGeneric<DAO extends GenericDAO, BEAN extends GenericBean & CompraVendaProduto> extends GenericRoute<DAO, BEAN> {

    private int selectedId = 0;
    private String whereField = "id_compra";
    
    /**
     * Creates new form CompraVendaRoute
     */
    public CompraVendaGeneric(Class<DAO> c_dao, Class<BEAN> c_bean, String title, int selectedId) {
        super(c_dao, c_bean);
        initComponents();
        
        this.selectedId = selectedId;
        if (title.endsWith("venda"))
            whereField = "id_venda";
        
        /**
         * Soma os produtos e mostra o total
         */
        this.store.subscribe("data", (value) -> {
            BigDecimal sum = new BigDecimal(0);
            ArrayList<BEAN> data = (ArrayList<BEAN>) value;
            try {
                for (int i = 0; i < data.size(); i++) {
                    BEAN bean = data.get(i);
                    BigDecimal valorUnitario = bean.getValorUnitario();
                    BigDecimal quantidade = new BigDecimal(bean.getQuantidade());
                    sum = sum.add(valorUnitario.multiply(quantidade));
                }
                
            } catch (Exception ex) {
                Alerts.error(null, "Erro ao executar a ação", String.format("%s", ex));
            }
           
            totalLabel.setText(String.format("Total: %s", GenericBean.formatNumber.format(sum)));
        });
        
        this.createSubscribersForTable(tableDados, (bool) -> {
            editarButton.setEnabled(bool);
            deletarButton.setEnabled(bool);
        });
        
        this.title.setText(String.format("Gerenciar %s", title.toLowerCase()));
    }
    
    /**
     * 
     * @return 
     */
    protected DAO getDaoInstance() {
        DAO dao = super.getDaoInstance();
        dao.where(whereField, selectedId);
        return dao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        adicionarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        deletarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();

        title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        title.setText("Compra venda");

        adicionarButton.setText("Adicionar produto");
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });

        editarButton.setText("Editar produto");
        editarButton.setEnabled(false);
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        deletarButton.setText("Deletar produto");
        deletarButton.setEnabled(false);
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });

        tableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableDados);
        if (tableDados.getColumnModel().getColumnCount() > 0) {
            tableDados.getColumnModel().getColumn(0).setResizable(false);
            tableDados.getColumnModel().getColumn(1).setResizable(false);
            tableDados.getColumnModel().getColumn(2).setResizable(false);
            tableDados.getColumnModel().getColumn(3).setResizable(false);
            tableDados.getColumnModel().getColumn(4).setResizable(false);
        }

        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        totalLabel.setText("Total: R$ 0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionarButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarButton)
                        .addGap(18, 18, 18)
                        .addComponent(deletarButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarButton)
                    .addComponent(editarButton)
                    .addComponent(deletarButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        title.getAccessibleContext().setAccessibleName("Titulo");
    }// </editor-fold>//GEN-END:initComponents

    private void openCompraVendaModal(Actions action) {
        try {
            CompraVendaEditor<DAO, BEAN> window = new CompraVendaEditor<>(c_dao, c_bean, selectedId, store, action);
            window.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent event) {
                    super.windowClosed(event);
                    store.set("edited", null);
                }
            });
            window.setVisible(true);
        } catch (Exception ex) {
            Alerts.error(null, "Erro ao executar a ação", String.format("%s", ex));
        }
    }
    
    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
        this.openCompraVendaModal(Actions.CREATE);
    }//GEN-LAST:event_adicionarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        this.openCompraVendaModal(Actions.EDIT);
    }//GEN-LAST:event_editarButtonActionPerformed

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        this.deleteSelected("Deletar produto", "o produto", "getProduto");
    }//GEN-LAST:event_deletarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JButton deletarButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDados;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
